# docker-compse.yml
version: "3.3"

services:
  app:
    build: .
    command: bash -c "bundle exec rails db:drop db:create db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app/base
    environment:
      DATABASE_HOSTNAME: 'db'
      DATABASE_USERNAME: 'root'
      DATABASE_PASSWORD: ''
      DATABASE_NAME: 'base'
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
    stdin_open: true
    tty: true
  sidekiq:
    build: .
    volumes:
      - .:/app/base
    links:
      - db
      - redis
    command: bundle exec sidekiq
    environment:
      DATABASE_HOSTNAME: 'db'
      DATABASE_USERNAME: 'root'
      DATABASE_PASSWORD: ''
      DATABASE_NAME: 'base'
      REDIS_URL: redis://redis:6379
  db:
    image: mysql:5.7.18
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  redis:
    image: redis
    environment:
      REDIS_URL: redis://redis:6379
